# Generated by Django 3.1.4 on 2021-09-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created',
            new_name='date_created',
        ),
    ]
