# Generated by Django 3.1.4 on 2021-09-22 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210921_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', '-date_created', 'title']},
        ),
    ]
