# Generated by Django 3.1.4 on 2021-09-25 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210925_1326'),
        ('projects', '0008_auto_20210922_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[(None, ''), ('up', 'Up Vote'), ('down', 'Down Vote')], max_length=100),
        ),
    ]
